[profile.default]
gas_reports = ["*"]
gas_reports_ignore = []
ignored_error_codes = []
optimizer = true
optimizer_runs = 999999
solc_version = "0.8.26"
verbosity = 3
evm_version = "cancun"

[profile.production]
build_info = true
sizes = true

[fuzz]
runs = 100

[invariant]
runs = 512            # The number of calls to make in the invariant tests
depth = 25            # The number of times to run the invariant tests
fail_on_revert = true # Fail the test if the contract reverts

[profile.ci.fuzz]
runs = 10_000

[profile.ci.invariant]
runs = 512
depth = 250

[rpc_endpoints]
localhost = "${LOCALHOST_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
world-chain-sepolia = "${WORLD_CHAIN_SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/api" }
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }
world-chain-sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.worldscan.org/api" }

# See more config options at https://github.com/foundry-rs/foundry/tree/master/crates/config
