[profile.default]
gas_reports = ["*"]
gas_reports_ignore = []
ignored_error_codes = []
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 4150
verbosity = 3
fork_block_number = 23_170_985
rpc_storage_caching = { chains = ["mainnet"], endpoints = "all" }
evm_version = "cancun"

[lint]
lint_on_build = false

[profile.production]
build_info = true
sizes = true

[fuzz]
runs = 100

[invariant]
runs = 512            # The number of calls to make in the invariant tests
depth = 25            # The number of times to run the invariant tests
fail_on_revert = true # Fail the test if the contract reverts

[profile.ci.fuzz]
runs = 10_000

[profile.ci.invariant]
runs = 512
depth = 250

[rpc_endpoints]
localhost = "${LOCALHOST_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
bsc = "${BSC_RPC_URL}"
monad = "${MONAD_RPC_URL}"
hyperevm = "${HYPEREVM_RPC_URL}"
soneium = "${SONEIUM_RPC_URL}"
moca = "${MOCA_RPC_URL}"
citrea = "${CITREA_RPC_URL}"
rise = "${RISE_RPC_URL}"
mantra = "${MANTRA_RPC_URL}"
base = "${BASE_RPC_URL}"
plasma = "${PLASMA_RPC_URL}"
0g = "${ZEROG_RPC_URL}"
fluent = "${FLUENT_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
linea = "${LINEA_RPC_URL}"
plume = "${PLUME_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}", url = "${MAINNET_VERIFIER_URL}", chain = 1 }
bsc = { key = "${ETHERSCAN_API_KEY}", url = "${BSC_VERIFIER_URL}", chain = 56 }
monad = { key = "${ETHERSCAN_API_KEY}", url = "${MONAD_VERIFIER_URL}", chain = 143 }
hyperevm = { key = "${ETHERSCAN_API_KEY}", url = "${HYPEREVM_VERIFIER_URL}", chain = 999 }
base = { key = "${ETHERSCAN_API_KEY}", url = "${BASE_VERIFIER_URL}", chain = 8453 }
plasma = { key = "${ETHERSCAN_API_KEY}", url = "${PLASMA_VERIFIER_URL}", chain = 9745 }
arbitrum = { key = "${ETHERSCAN_API_KEY}", url = "${ARBITRUM_VERIFIER_URL}", chain = 42161 }
linea = { key = "${ETHERSCAN_API_KEY}", url = "${LINEA_VERIFIER_URL}", chain = 59144 }
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "${SEPOLIA_VERIFIER_URL}", chain = 11155111 }

# See more config options at https://github.com/foundry-rs/foundry/tree/master/crates/config
