name: Forge Coverage

on:
  push:
    branches:
      - main
  pull_request:

permissions: write-all

jobs:
  check:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install lcov
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Run coverage
        id: coverage
        env:
          MNEMONIC: ${{ secrets.MNEMONIC_FOR_TESTS }}
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: make coverage

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v4.1.22
        with:
          coverage-files: lcov.info
          artifact-name: code-coverage-report
          minimum-coverage: 95
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
